python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_2/rest/services/PLAN_ZG_2020/MapServer/0" -l 12 -o "res/res.gdb"
python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/bdcj_1/MapServer/1" -o "res/suplicmap.gdb"
python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/bdcj_1/MapServer/2" -o "res/suplicmap.gdb"
python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/bdcj_1/MapServer/3" -o "res/suplicmap.gdb"
python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/bdcj_1/MapServer/4" -o "res/suplicmap.gdb"
python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/bdcj_1/MapServer/5" -o "res/suplicmap.gdb"
python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/bdcj_1/MapServer/6" -o "res/suplicmap.gdb"
python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/bdcj_1/MapServer/7" -o "res/suplicmap.gdb"
python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/bdcj_1/MapServer/8" -o "res/suplicmap.gdb"
python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/bdcj_1/MapServer/9" -o "res/suplicmap.gdb"

python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/BDCJ/MapServer/0" -o "res/suplicmap.gdb"
python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/BDCJ/MapServer/1" -o "res/suplicmap.gdb"
python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/BDCJ/MapServer/2" -o "res/suplicmap.gdb"
python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/BDCJ/MapServer/3" -o "res/suplicmap.gdb"
python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/BDCJ/MapServer/4" -o "res/suplicmap.gdb"
python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/BDCJ/MapServer/5" -o "res/suplicmap.gdb"
python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/BDCJ/MapServer/6" -o "res/suplicmap.gdb"
python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/BDCJ/MapServer/7" -o "res/suplicmap.gdb"
python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/BDCJ/MapServer/8" -o "res/suplicmap.gdb"
python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/BDCJ/MapServer/9" -o "res/suplicmap.gdb"
python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/BDCJ/MapServer/10" -o "res/suplicmap.gdb"
python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/BDCJ/MapServer/11" -o "res/suplicmap.gdb"

python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/BDDJ_1/MapServer/0" -o "res/suplicmap.gdb"

python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/BDDJ/MapServer/0" -o "res/suplicmap.gdb"
python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/BDDJ/MapServer/1" -o "res/suplicmap.gdb"
python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/BDDJ/MapServer/2" -o "res/suplicmap.gdb"
python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/BDDJ/MapServer/3" -o "res/suplicmap.gdb"
python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/BDDJ/MapServer/4" -o "res/suplicmap.gdb"
python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/BDDJ/MapServer/5" -o "res/suplicmap.gdb"
python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/BDDJ/MapServer/6" -o "res/suplicmap.gdb"
python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/BDDJ/MapServer/7" -o "res/suplicmap.gdb"
python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/BDDJ/MapServer/8" -o "res/suplicmap.gdb"

python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/BLDG_ZHUANG2010/MapServer/0" -o "res/suplicmap.gdb"
python suplicmap_vector.py -u "http://suplicmap.pnr.sz/dynaszmap_1/rest/services/BLDG_ZHUANG2010/MapServer/1" -o "res/suplicmap.gdb"

pause